### PR TITLE
add model checksums

### PR DESCRIPTION
**Pull request by kpedro88**
for https://github.com/cms-sw/cmssw/issues/43695

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
[@cms-sw/reconstruction-l2](https://github.com/orgs/cms-sw/teams/reconstruction-l2) please sign so we can move to the next step of the plan in https://github.com/cms-sw/cmssw/issues/43695

**Comment by smuzaffar** [comment]
@kpedro88 , why not run tests with https://github.com/cms-sw/cmssw/pull/43696 to make sure  `cmsTritonConfigTool` properly process the config.pbtxt change here?

**Comment by kpedro88** [comment]
@smuzaffar I've run such tests privately. I was hoping to avoid having to list the N-1 related PRs in every PR in this group to run such tests centrally. The changes in the cms-data PRs are harmless taken alone, so it should be fine to just integrate them first.

**Comment by smuzaffar** [comment]
+externals

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
