### PR TITLE
Updated model files to play nicely with GPU backend

### PR DESCRIPTION
**Pull request by ssrothman**
Analogous to https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2 

Updates model configs to play nicely with SonicTriton pytorch GPU backend

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
* pull_requests = https://github.com/cms-sw/cmsdist/pull/8324, https://github.com/cms-data/HeterogeneousCore-SonicTriton/pull/2, https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2, https://github.com/cms-sw/cmssw/pull/40814

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@cms-sw/reconstruction-l2 we must bypass your signature because the PR that need this external was already merged, sorry for that. Follow up in issue https://github.com/cms-sw/cmssw/issues/40938

**Comment by perrotta** [comment]
merge

**Pull request merged**
