### PR TITLE
Adding models files for DeepSC algorithm

### PR DESCRIPTION
**Pull request by valsdav**
This PR goes along the one (https://github.com/cms-sw/cmssw/pull/37115) for the inclusion of the DeepSC algorithm. 

It includes the first version of the training for EOY 2018 ECAL conditions.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37115#issuecomment-1100714495

**Comment by smuzaffar** [comment]
+externals
Only new data files tested via https://github.com/cms-sw/cmssw/pull/37115)

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37115#issuecomment-1150407445

**Comment by valsdav** [comment]
Hi! I guess we would need to merge also this PR, before https://github.com/cms-sw/cmssw/pull/37115 gets integrated in the next IB, right?

**Comment by smuzaffar** [comment]
correct, @perrotta @qliphy can you please merge this

**Comment by perrotta** [comment]
+1
- Just forgot... Thank you for the remainder

**Pull request merged**
